# Generated by Django 3.1.3 on 2021-03-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drag_forces_sim', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drag_Object',
            new_name='DragObject',
        ),
        migrations.RenameField(
            model_name='dragobject',
            old_name='current_speed',
            new_name='currentSpeed',
        ),
        migrations.RenameField(
            model_name='dragobject',
            old_name='drag_coeficient',
            new_name='dragCoeficient',
        ),
        migrations.RenameField(
            model_name='dragobject',
            old_name='gravitational_constant',
            new_name='gravitationalConstant',
        ),
        migrations.RenameField(
            model_name='dragobject',
            old_name='obj_mass',
            new_name='objMass',
        ),
        migrations.RenameField(
            model_name='dragobject',
            old_name='obj_name',
            new_name='objName',
        ),
    ]
